//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class Applications : ServiceType
    {
        string fApplicationName;
        public string ApplicationName
        {
            get { return fApplicationName; }
            set { SetPropertyValue<string>(nameof(ApplicationName), ref fApplicationName, value); }
        }
        string fApplicationVersion;
        public string ApplicationVersion
        {
            get { return fApplicationVersion; }
            set { SetPropertyValue<string>(nameof(ApplicationVersion), ref fApplicationVersion, value); }
        }
        string fApplicationDescription;
        public string ApplicationDescription
        {
            get { return fApplicationDescription; }
            set { SetPropertyValue<string>(nameof(ApplicationDescription), ref fApplicationDescription, value); }
        }
        string fApplicationPath;
        public string ApplicationPath
        {
            get { return fApplicationPath; }
            set { SetPropertyValue<string>(nameof(ApplicationPath), ref fApplicationPath, value); }
        }
    }

}
