//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class Device : XPObject
    {
        string fDeviceName;
        public string DeviceName
        {
            get { return fDeviceName; }
            set { SetPropertyValue<string>(nameof(DeviceName), ref fDeviceName, value); }
        }
        DateTime fFirstCheckin;
        public DateTime FirstCheckin
        {
            get { return fFirstCheckin; }
            set { SetPropertyValue<DateTime>(nameof(FirstCheckin), ref fFirstCheckin, value); }
        }
        string fOsVersion;
        public string OsVersion
        {
            get { return fOsVersion; }
            set { SetPropertyValue<string>(nameof(OsVersion), ref fOsVersion, value); }
        }
        string fSystemUptime;
        public string SystemUptime
        {
            get { return fSystemUptime; }
            set { SetPropertyValue<string>(nameof(SystemUptime), ref fSystemUptime, value); }
        }
        string fArchitecture;
        public string Architecture
        {
            get { return fArchitecture; }
            set { SetPropertyValue<string>(nameof(Architecture), ref fArchitecture, value); }
        }
        string fSerialNumber;
        public string SerialNumber
        {
            get { return fSerialNumber; }
            set { SetPropertyValue<string>(nameof(SerialNumber), ref fSerialNumber, value); }
        }
        string fDeviceType;
        public string DeviceType
        {
            get { return fDeviceType; }
            set { SetPropertyValue<string>(nameof(DeviceType), ref fDeviceType, value); }
        }
        string fManufacturer;
        public string Manufacturer
        {
            get { return fManufacturer; }
            set { SetPropertyValue<string>(nameof(Manufacturer), ref fManufacturer, value); }
        }
        string fAssetNumber;
        public string AssetNumber
        {
            get { return fAssetNumber; }
            set { SetPropertyValue<string>(nameof(AssetNumber), ref fAssetNumber, value); }
        }
        string fModel;
        public string Model
        {
            get { return fModel; }
            set { SetPropertyValue<string>(nameof(Model), ref fModel, value); }
        }
        [Association(@"ServiceTypeReferencesDevice")]
        public XPCollection<ServiceType> ServiceTypes { get { return GetCollection<ServiceType>(nameof(ServiceTypes)); } }
    }

}
