//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class Storage : ServiceType
    {
        string fStorageType;
        public string StorageType
        {
            get { return fStorageType; }
            set { SetPropertyValue<string>(nameof(StorageType), ref fStorageType, value); }
        }
        string fStorageSize;
        public string StorageSize
        {
            get { return fStorageSize; }
            set { SetPropertyValue<string>(nameof(StorageSize), ref fStorageSize, value); }
        }
        string fStorageUtilization;
        public string StorageUtilization
        {
            get { return fStorageUtilization; }
            set { SetPropertyValue<string>(nameof(StorageUtilization), ref fStorageUtilization, value); }
        }
        string fStorageSpeed;
        public string StorageSpeed
        {
            get { return fStorageSpeed; }
            set { SetPropertyValue<string>(nameof(StorageSpeed), ref fStorageSpeed, value); }
        }
        string fStorageHealth;
        public string StorageHealth
        {
            get { return fStorageHealth; }
            set { SetPropertyValue<string>(nameof(StorageHealth), ref fStorageHealth, value); }
        }
        string fStorageName;
        public string StorageName
        {
            get { return fStorageName; }
            set { SetPropertyValue<string>(nameof(StorageName), ref fStorageName, value); }
        }
        string fDriveLetter;
        public string DriveLetter
        {
            get { return fDriveLetter; }
            set { SetPropertyValue<string>(nameof(DriveLetter), ref fDriveLetter, value); }
        }
        string fFileTypeSystem;
        public string FileTypeSystem
        {
            get { return fFileTypeSystem; }
            set { SetPropertyValue<string>(nameof(FileTypeSystem), ref fFileTypeSystem, value); }
        }
    }

}
