//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class Hardware : ServiceType
    {
        string fCpuModel;
        public string CpuModel
        {
            get { return fCpuModel; }
            set { SetPropertyValue<string>(nameof(CpuModel), ref fCpuModel, value); }
        }
        string fCpuUtilization;
        public string CpuUtilization
        {
            get { return fCpuUtilization; }
            set { SetPropertyValue<string>(nameof(CpuUtilization), ref fCpuUtilization, value); }
        }
        string fMemoryTotal;
        public string MemoryTotal
        {
            get { return fMemoryTotal; }
            set { SetPropertyValue<string>(nameof(MemoryTotal), ref fMemoryTotal, value); }
        }
        string fRamUtilization;
        public string RamUtilization
        {
            get { return fRamUtilization; }
            set { SetPropertyValue<string>(nameof(RamUtilization), ref fRamUtilization, value); }
        }
    }

}
