//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class Network : ServiceType
    {
        string fIpAddress;
        public string IpAddress
        {
            get { return fIpAddress; }
            set { SetPropertyValue<string>(nameof(IpAddress), ref fIpAddress, value); }
        }
        string fMacAddress;
        public string MacAddress
        {
            get { return fMacAddress; }
            set { SetPropertyValue<string>(nameof(MacAddress), ref fMacAddress, value); }
        }
        string fDefaultGateway;
        public string DefaultGateway
        {
            get { return fDefaultGateway; }
            set { SetPropertyValue<string>(nameof(DefaultGateway), ref fDefaultGateway, value); }
        }
        string fNetworkSpeed;
        public string NetworkSpeed
        {
            get { return fNetworkSpeed; }
            set { SetPropertyValue<string>(nameof(NetworkSpeed), ref fNetworkSpeed, value); }
        }
        string fActiveNetworkInterface;
        public string ActiveNetworkInterface
        {
            get { return fActiveNetworkInterface; }
            set { SetPropertyValue<string>(nameof(ActiveNetworkInterface), ref fActiveNetworkInterface, value); }
        }
        bool fIsStatic;
        public bool IsStatic
        {
            get { return fIsStatic; }
            set { SetPropertyValue<bool>(nameof(IsStatic), ref fIsStatic, value); }
        }
    }

}
