//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class PowerPerformance : ServiceType
    {
        string fPowerPlan;
        public string PowerPlan
        {
            get { return fPowerPlan; }
            set { SetPropertyValue<string>(nameof(PowerPlan), ref fPowerPlan, value); }
        }
        string fSleepTimer;
        public string SleepTimer
        {
            get { return fSleepTimer; }
            set { SetPropertyValue<string>(nameof(SleepTimer), ref fSleepTimer, value); }
        }
        string fCpuTemp;
        public string CpuTemp
        {
            get { return fCpuTemp; }
            set { SetPropertyValue<string>(nameof(CpuTemp), ref fCpuTemp, value); }
        }
    }

}
