//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class Processes : ServiceType
    {
        string fRunningProcesses;
        public string RunningProcesses
        {
            get { return fRunningProcesses; }
            set { SetPropertyValue<string>(nameof(RunningProcesses), ref fRunningProcesses, value); }
        }
        string fTopMemoryProcesses;
        public string TopMemoryProcesses
        {
            get { return fTopMemoryProcesses; }
            set { SetPropertyValue<string>(nameof(TopMemoryProcesses), ref fTopMemoryProcesses, value); }
        }
        string fProcessCPUsage;
        public string ProcessCPUsage
        {
            get { return fProcessCPUsage; }
            set { SetPropertyValue<string>(nameof(ProcessCPUsage), ref fProcessCPUsage, value); }
        }
        string fInstalledApplications;
        public string InstalledApplications
        {
            get { return fInstalledApplications; }
            set { SetPropertyValue<string>(nameof(InstalledApplications), ref fInstalledApplications, value); }
        }
        string fServicesStatus;
        public string ServicesStatus
        {
            get { return fServicesStatus; }
            set { SetPropertyValue<string>(nameof(ServicesStatus), ref fServicesStatus, value); }
        }
    }

}
