//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gitec.InfoServe.CommonLib.Data
{

    public partial class SecurityLogs : ServiceType
    {
        string fUserLoginHistory;
        public string UserLoginHistory
        {
            get { return fUserLoginHistory; }
            set { SetPropertyValue<string>(nameof(UserLoginHistory), ref fUserLoginHistory, value); }
        }
        string fFailedLoginAttempts;
        public string FailedLoginAttempts
        {
            get { return fFailedLoginAttempts; }
            set { SetPropertyValue<string>(nameof(FailedLoginAttempts), ref fFailedLoginAttempts, value); }
        }
        string fFirewallStatus;
        public string FirewallStatus
        {
            get { return fFirewallStatus; }
            set { SetPropertyValue<string>(nameof(FirewallStatus), ref fFirewallStatus, value); }
        }
        string fAntivirusStatus;
        public string AntivirusStatus
        {
            get { return fAntivirusStatus; }
            set { SetPropertyValue<string>(nameof(AntivirusStatus), ref fAntivirusStatus, value); }
        }
        string fWindowsDefenderStatus;
        public string WindowsDefenderStatus
        {
            get { return fWindowsDefenderStatus; }
            set { SetPropertyValue<string>(nameof(WindowsDefenderStatus), ref fWindowsDefenderStatus, value); }
        }
    }

}
